services:
  # docker compose up mysql -d
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db0
      - MYSQL_USER=whoami
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  # docker compose down mysql -v
